apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dummyapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyapi
  template:
    metadata:
      labels:
        app: dummyapi
    spec:
      containers:
      - name: dummyapi
        image: betazoide/flask:2.0.0
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30s # 1 hour
      - setWeight: 20
      - pause: 
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s