apiVersion: v1
kind: Service
metadata:
  name: dummyapi
  labels:
    app: dummyapi
spec:
  selector:
    app: dummyapi
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummyapi-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyapi
  template:
    metadata:
      labels:
        app: dummyapi
        version: v1
    spec:
      containers:
      - name: dummyapi
        image: betazoide/flask:2.0.0
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
            httpGet:
              path: /
              port: http
        readinessProbe:
            httpGet:
              path: /
              port: http